name: ft-catan
services:

  nestjs:
    build:
      context: ./backend
    container_name: nestjs
    restart: unless-stopped
    networks:
      - ft-network
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:18
    container_name: postgres
    env_file:
      - .env
    #using the .env file directly in the compose to set user
    volumes:
      - postgres-data:/var/lib/postgresql/
    ports:
      - "5432:5432"
    networks:
      - ft-network
    restart: unless-stopped

# --- Volumes --- #
volumes:
  postgres-data:

# --- Networks --- #

networks:
  ft-network:

# --- Secrets --- #
